apiVersion: v1
kind: Service
metadata:
  name: ticker-candles
spec:
  selector:
    app: ticker-candles
  ports:
  - protocol: TCP
    port: 9002
    targetPort: 9002
    nodePort: 30228
  type: NodePort
