apiVersion: v1
kind: Service
metadata:
  name: postgres-ticker-candles
  labels:
    app: postgres-ticker-candles
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres-ticker-candles
